services:
  postgres:
    image: postgres:16
    container_name: fs_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - fs_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fs_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: fs_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - fs_minio:/data

volumes:
  fs_pg:
  fs_minio:
